.ant-job:
  stage: test
  image: openjdk:11
  before_script:
  - apt-get update -yqq
  - apt-get install ant ivy -yqq

php-pdftk:
  extends: .ant-job
  script:
    - ant -lib /usr/share/java
    - echo -e '#!/bin/bash\njava -cp' `pwd`'/build/jar/pdftk.jar:'`pwd`'/lib/bcprov-jdk15on-1.51.jar:'`pwd`'/lib/commons-lang3-3.7.jar com.gitlab.pdftk_java.pdftk "$@"' > /usr/bin/pdftk
    - chmod +x /usr/bin/pdftk
    - apt-get install php-mbstring phpunit composer -yqq
    - git clone --depth 1 https://github.com/marcvinyals/php-pdftk
    - cd php-pdftk
    - composer install
    - pdftk --version
    - phpunit

test:
  extends: .ant-job
  script:
    - apt-get install poppler-utils -yqq
    - ant -lib /usr/share/java test-resolve
    - ant -lib /usr/share/java -lib ./lib test
    - perl -ne 'm/Total.*?([0-9]{1,3})%/; print "Coverage $1%\n"' coverage/index.html
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir public/
    - mv coverage/ public/
  artifacts:
    paths:
      - public/
  only:
    - master

.gradle-job:
  stage: test
  image: gradle:latest
  variables:
    GRADLE_VERSION: "5.0"
  script:
    - gradle wrapper --gradle-version=$GRADLE_VERSION
    - ./gradlew shadowJar
    - java -jar build/libs/pdftk-all.jar --version

gradle:
  extends: .gradle-job
  artifacts:
    paths:
    - build/libs/pdftk-all.jar
    expire_in: 1 month

gradle-4.10.3:
  extends: .gradle-job
  variables:
    GRADLE_VERSION: "4.10.3"

gradle-4.0:
  extends: .gradle-job
  variables:
    GRADLE_VERSION: "4.0"

spotless:
  extends: .gradle-job
  script:
    - gradle spotlessCheck
